# -*- coding: utf-8 -*-
"""
Y1 Computing Project
Minseo Kim
Estimate of Hubble's Constant': (7.144 +/- 0.002) * 10**2 km/s/MPc
Some parts of the project were modified from AI-generated code. 
Link: https://gemini.google.com/share/efd1ed89a047
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit


#List of Constants
c = 2.9979e8 #Speed of light
lambda_e = 4.861e-7 #Emitted wavelength
MPc = 3.086e22 #Length of 1 megaparsec in metres


'''
Equations
v = H_0*D --- eq.1
lambda_obs = c/freq_obs, where freq_obs is determined from the data.
lambda_obs/lambda_e = sqrt(c+v/c-v), --- eq.2
after some manipulation it becomes
v = c*(lambda_obs**2 - lambda_e**2)/(lambda_obs**2-lambda_e**2) --- eq.3
Plotting v against D, the gradient will be H_0.
'''

'''
Error propagation
Since the equipment used in making the measurements is unknown, 
The standard deviation of the normal curve fitted to the spectral data was used.
sigma_lambda_obs_relative = sigma_freq_relative (v = f*lambda)
v_error_relative = (np.sqrt(2)*lambda_0_error*
                    ((lambda_0**2 - lambda_e**2)**(-1) + 
                     (lambda_0**2 + lambda_e**2)**(-1)))
from eq.3 in the Equations section. 
Unfortunately, there is no meaningful way to estimate the uncertainty
for the galaxy distance measurements. As they are separate measurements of 
different galaxies, I cannot use statistical methods to estimate the uncertainty. 
'''


#Sifting through the distance data
#This section was modified from code generated by Gemini AI
dist_data_raw = pd.read_csv("C:\\Users\\user\\OneDrive - Imperial College London\\Y1_Computing\\Project_Data\\dist_data.txt",
                            header = 5, sep = '\t', engine = 'python')
dist_data_raw2 = dist_data_raw.to_numpy().tolist()


#Removing the invalid values
dist_data_valid = []
for i in range(0, len(dist_data_raw2)):
    if (dist_data_raw2[i][4] != 'E'):
        dist_data_valid.append(dist_data_raw2[i])


#Creating separate numpy arrays for the distance measurements and expt no.
dist_array_raw = np.asarray(dist_data_valid)
dist_array_raw = dist_array_raw.flatten()
dist_expt_no = dist_array_raw[2::5].astype(int).tolist()
dist_array = dist_array_raw[3::5].astype(float).tolist()


#Sifting through the spectral data 
HBeta_raw = pd.read_csv("C:\\Users\\user\\OneDrive - Imperial College London\\Y1_Computing\\Project_Data\\SpectralData_Hbeta.csv",
                          header = 4, sep = ',', engine = 'python')
HBeta_raw2 = HBeta_raw.to_numpy().tolist()
HBeta_raw2 = np.asarray(HBeta_raw2)


#Creating 2 lists for the frequency and spectra respectively
HBeta_raw2 = np.matrix.transpose(HBeta_raw2)
HBeta_freq = HBeta_raw2[0::2].tolist()
HBeta_spectra = HBeta_raw2[1::2].tolist()


#Creating lists containing only the valid spectral data measurements
HBeta_index = HBeta_raw.columns.tolist()
HBeta_index = np.asarray(HBeta_index[::2]).astype(int) #removing duplicates
HBeta_index_valid, HBeta_freq_valid, HBeta_spectra_valid = [], [], []
for i in range(0, len(HBeta_index)):
    if HBeta_index[i] in dist_expt_no:
        HBeta_index_valid.append(HBeta_index[i])
        HBeta_freq_valid.append(HBeta_freq[i])
        HBeta_spectra_valid.append(HBeta_spectra[i])


#Linear indexing to reorder the distance data lists
def lin_index(list1, list2):
    list3 = []
    for i in range(0, len(list1)):
        for j in range(0, len(list1)):
            if list1[i] != list2[j]:
                continue
            else:
                list3.append(j)
                break
    return list3


#Sorting distance data lists to match expt no with spectral data
#dist_array_sorted contains the final dist data used for the calculation of H_0
index = lin_index(HBeta_index_valid, dist_expt_no)
dist_expt_no_sorted = []
dist_array_sorted = []
for i in range(0, len(index)):
    dist_expt_no_sorted.append(dist_expt_no[index[i]])
    dist_array_sorted.append(dist_array[index[i]])
    
    
#linear search to find an estimate of the peak frequency
#finds the frequency value with the highest spectra 
def lin_search(list0):
    peak = 0
    for i in range(1, len(list0)):
        if list0[i] > list0[peak]:
            peak = i
    return peak
    
#the modified normal distribution function
def gaussian(x, sigma, mu, A, m, y_0):
    lin = y_0 + m*x
    normal = A*np.exp((-(x-mu)**2)/(2*sigma**2))
    y = lin + normal
    return y


#Analysing spectral data to find lambda_0
#The function guess_m was modified from code generated by Gemini AI
freq_0 = [] #storing 25 instances of peak frequencies
spectra_stdev = [] #storing 25 standard deviations for each set of data
for i in range(0, len(index)):
    guess_sigma = 1e13/6
    guess_mu = HBeta_freq_valid[i][lin_search(HBeta_spectra_valid[i])]  
    def guess_m(list1, list2):
        y_1 = np.mean(list1[0:20])
        y_2 = np.mean(list1[-20:])
        dy = ((y_2-y_1)/(list1[len(list1)-1]-list1[0]))/20
        dx = list2[len(list1)-1] - list2[0]
        return dy/dx      
    guess_y_0 = (HBeta_spectra_valid[i][0] 
                 - guess_m(HBeta_spectra_valid[i], HBeta_freq_valid[i])*HBeta_freq_valid[i][0])
    guess_A = ((HBeta_spectra_valid[i][lin_search(HBeta_spectra_valid[i])]) 
               - guess_m(HBeta_spectra_valid[i], HBeta_freq_valid[i])*HBeta_freq_valid[i][lin_search(HBeta_spectra_valid[i])]
               - guess_y_0)

    p0 = [guess_sigma, guess_mu, guess_A, guess_m(HBeta_spectra_valid[i], HBeta_freq_valid[i]), guess_y_0]
    fit, cov = curve_fit(gaussian, HBeta_freq_valid[i], HBeta_spectra_valid[i], p0 = p0)
    #The curve_fit occasionally produces negative values for standard deviation
    #This is due to the sigma**2 part of the gaussian function
    #This is 'artificially' corrected by using the absolute value
    fit[0] = abs(fit[0]) 
    spectra_stdev.append(fit[0])
    freq_0.append(fit[1])


#finding observed wavelength, lambda_0
lambda_0 = c/(np.array(freq_0))
#finding redshifted velocity, v_redshift
v_redshift = c*(lambda_0**2 - lambda_e**2)/(lambda_0**2 + lambda_e**2)
v_redshift = v_redshift.tolist()
#plotting
plt.grid()
plt.xlabel("Galaxy Distance/MPc") 
plt.ylabel("Redshifted Velocity/ms^-1") 
plt.title("Plot of v against D") 
plt.scatter(dist_array_sorted, v_redshift)


#Estimating the uncertainty in the v values
freq_0_relative_error = spectra_stdev/np.sqrt(len(HBeta_freq_valid[0]))/freq_0
lambda_0_error = freq_0_relative_error*lambda_0
v_error_relative = (np.sqrt(2)*lambda_0_error*
                    ((lambda_0**2 - lambda_e**2)**(-1) + 
                     (lambda_0**2 + lambda_e**2)**(-1)))


#finding line of best fit
fit_H0, cov_H0 = np.polyfit(dist_array_sorted, v_redshift, 1, w = 1/v_error_relative, cov = 'unscaled')
plt.plot(dist_array_sorted, np.polyval(fit_H0, dist_array_sorted))
plt.show()
print("Estimated Hubble's constant:", fit_H0[0], "+/-", np.sqrt(cov_H0[0][0]), "m/s/MPc")





